name: dash-env
dependencies:
- pip=8.1.2=py35_0
- python=3.5.2=0
- setuptools=23.0.0=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - django==1.9.8
  - mongoengine==0.10.6
  - psycopg2==2.6.2
  - pymongo==3.3.0
