# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(default='False', max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('item_thumb', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user_image', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('cakeday', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('holiday', models.CharField(max_length=50)),
                ('med_provider', models.CharField(max_length=50)),
                ('med_plan', models.CharField(max_length=50)),
                ('dent_provider', models.CharField(max_length=50)),
                ('dent_plan', models.CharField(max_length=50)),
                ('curr_project', models.CharField(max_length=50)),
                ('pre_project', models.CharField(max_length=50)),
                ('assign_asset', models.CharField(max_length=1000)),
                ('sent_note', models.CharField(max_length=200)),
                ('recv_note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('inc', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('creator_id', models.CharField(default='0', max_length=255)),
                ('assigned_user_id', models.CharField(max_length=500)),
                ('asset', models.CharField(max_length=500)),
                ('location', models.CharField(default='', max_length=1000)),
                ('signedoff', models.BooleanField(default=False)),
                ('flagdelete', models.BooleanField(default=False)),
            ],
        ),
    ]
