# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcore', '0002_auto_20160729_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, size=None),
        ),
    ]
