# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashcore', '0003_auto_20160729_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='member_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='asset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_user_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='No Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
