# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
