# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20160707_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(default=0, verbose_name='start date'),
        ),
    ]
