# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20160707_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
